[project]
name = "neuron-chess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.11"
dependencies = [
    "argparse>=1.4.0",
    "chess>=1.11.2",
    "ipykernel>=7.1.0",
    "numpy>=2.4.1",
    "pip>=25.3",
]
